### ISSUE TITLE
Children example: using a Group?

### ISSUE THREAD

**Issue by jamesplease** [bmcmahen/react-meets-swiftui#1]
:wave: Hey there! Really cool repo. I've already learned a lot from the 3 examples you've put together.

I'm still _super_ new to Swift, but one idea I had for [this example](https://github.com/bmcmahen/react-meets-swiftui/blob/master/Children.md#swiftui) – and you may have already thought of this – is to update `content` to expect a Group instead of a Text. That way, you can return whatever you'd like by wrapping it in the Group.

_(Note: I haven't tested this code, so it might not compile. Also, this general approach might not even be sound. And there is likely a better way altogether!)_

```diff
import SwiftUI

struct Page : View {
    var body: some View {
        Layout() {
+            Group {
                Text("This is the page content")
+            }
        }
    }
}

struct Layout : View {

-   var content: () -> Text
+   var content: () -> Group

    var body: some View {
        VStack {
            Text("This is the layout")
            content()
        }
    }
}
```

**Comment by bmcmahen** [comment]
Hey! Thanks for the idea. Just tried it, but unfortunately it doesn't compile.  It complains that Group is a generic which requires an argument -- something like this:

```swift
var content: () -> Group<Text>
```

I assume there's gotta be some type that's equivalent to React's `React.ReactNode` .... but I have no clue what it is.

**Comment by jamesplease** [comment]
Ah, shucks. I should have tried it out before typing this issue up (I lied and told myself I was going to go to sleep instead). 

> I assume there's gotta be some type that's equivalent to React's React.ReactNode .... but I have no clue what it is.

I'm digging around to see if I can figure this out. I'll update this issue if I find anything, but for now I'll go ahead and close it since the original idea doesn't work.
