### ISSUE TITLE
Children: Using ViewBuilder?

### ISSUE THREAD

**Issue by johnsusek** [bmcmahen/react-meets-swiftui#4]
I've also been looking into how to do children, and started reading up on ViewBuilder:

https://developer.apple.com/documentation/swiftui/viewbuilder

It seems like this might be helpful, but struggling to grok it. Thought I would mention it in case it helps

**Comment by bmcmahen** [comment]
This looks really promising. I'll see if I can figure it out. I'm kinda hoping this video gives us some more details: https://developer.apple.com/videos/play/wwdc2019/237/

**Comment by bmcmahen** [comment]
I've got a working example [here](https://github.com/bmcmahen/react-meets-swiftui/blob/master/Children.md). Can't say I fully understand it, but it's a start...
