### ISSUE TITLE
Redux (Binding to an External Store) @ObjectBinding

### ISSUE THREAD

**Issue by sami616** [bmcmahen/react-meets-swiftui#5]
Hiya, and thanks for the amazing resource for react devs!

My understanding on this is still a little vague but i _think_ using `@EnvironmentObject` instead of `@ObjectBinding` is a little closer to a redux setup seeing as with `@EnvironmentObject` you  can directly access a central source of truth/store from nested views without prop drilling.

**Comment by bmcmahen** [comment]
hey @sami616 ! Yeah, that's interesting. Redux's provider component does use context and it redux typically is used to access app-wide state, so you're right that it's probably closer to `@EnvironmentObject`. I'll update that example with a note & reference to the context page.
